services:
  - type: web
    name: braniac-backend
    env: node
    region: oregon
    branch: main
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    autoDeploy: true
    env:
      - key: NODE_ENV
        value: production
        sync: false
