services:
  - type: web
    name: braniac-backend-main
    env: node
    region: oregon
    branch: main
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: braniac-backend-master
    env: node
    region: oregon
    branch: master
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
